### ISSUE TITLE
Zoom effect bug

### ISSUE THREAD

**Issue by JstormZx** [cvzi/darkmodewallpaper#25] opened 2021-07-08 12:45 UTC
Hi.
I noticed a minor bug in the app's operation

I'll try to be as specific as possible even if the bug is minor.

Device:
Xiaomi Redmi note 10 pro,
Android 11, Miui 12.5.3.0 RKFMIXM.

Launcher: 
Nova launcher prime. 7.0.34

Imported wallpaper immediately after first launch.

Problem:
**I noticed the wallpapers were slightly off center, leaning towards the right side of the screen**

This broke pretty much the entire app afterwards. No matter what you do. Remove the imported wallpaper and select a new one from the gallery, it was still off centered.
To confirm that this is a bug, I repeated everything I did during setup:

• Imported current wallpaper at the initial prompt.
• Turned off "use day time image" in night time settings.
• Selected a new dark mode wallpaper from gallery.
• Turned on zoom effect (**the real culprit here after investigation**)
• Applied as home screen wallpaper.

After successfully being applied, the wallpaper was shifted slightly to the right. And the zoom effect didn't work. I am positive either nova launcher or Miui has something to do with this. But I disabled nova 7's wallpaper zoom effects to make sure it didn't conflict with dark mode live wallpaper. And it still happened.

I fixed it by clearing the app data and restarting the initial setup process. This time, selecting a wallpaper from the gallery instead and disabling zoom effect.
The wallpapers look and change fine now.

Conclusion: 
The zoom effect feature is bugged on my device.
And possibly could be on other phones as well.

Thanks and I hope I didn't write too much 🙂
This is actually my first issue on GitHub. Heck, the first comment I've ever typed on GitHub. So I have no idea how things work here.

Hope you had a splendid day.

Normal wallpaper:
![Screenshot_2021-07-08-13-32-01-664_com teslacoilsw launcher](https://user-images.githubusercontent.com/87129254/124922190-2b35f180-dff1-11eb-9d36-47230c69c6ad.jpg)

App settings responsible for bug:
![Screenshot_2021-07-08-13-32-53-509_com github cvzi darkmodewallpaper](https://user-images.githubusercontent.com/87129254/124922201-2d984b80-dff1-11eb-9e91-75fc2ff946e5.jpg)

Bugged wallpaper:
![Screenshot_2021-07-08-13-32-56-929_com teslacoilsw launcher](https://user-images.githubusercontent.com/87129254/124922211-2f620f00-dff1-11eb-9c5f-bbbb9cc87231.jpg)

**Comment by cvzi** [comment] 2021-07-08 18:02
Thanks for the detailed explanation. Very good first issue!

**Comment by cvzi** [comment] 2021-07-08 18:15
The zoom effect is currently not centered but can zoom slightly to the right. That explains why it is shifted to the right. It zoomed in and then it didn't zoom out completely.
(I put your correct and wrong image over each other and tried to match the white logo in the center, you can see that the size of the logo does not match i.e. one is slightly zoomed in)

It should have zoomed out completely on home screen but it didn't. I don't know if this is a bug in the app or in Miui or Nova.

I couldn't reproduce it on a plain Android 11 with Nova, so might be Miui related. I will keep investigating 🙂

![zoomedin](https://user-images.githubusercontent.com/8470684/124970422-29d3eb80-e028-11eb-94c7-4722e71d954e.jpg)

**Comment by JstormZx** [comment] 2021-07-09 11:27
Ah thanks for that...it's could be miui's fault. I also tried nova 7 zoom effects and that's also kinda working but also slightly broken. So... anyway it's cool.

 Thanks for the quick reply and compliment and I guess I'll wait for your investigation results.

Hehe
Thanks for the app I'll never stop using it lol. And have a ridiculously good day. 🙃

**Comment by cvzi** [comment] 2022-08-03 18:34
I think this should be fixed in the newest version. If not fixed, please re-open the issue.

**Closed by cvzi** 2022-08-03 18:34 UTC
Labels: bug
