### ISSUE TITLE
Select random wallpapers from a pool

### ISSUE THREAD

**Issue by azmeuk** [cvzi/darkmodewallpaper#226] opened 2024-10-03 07:35 UTC
It would be nice if users could select several light ant dark wallpapers, and the app would randomly select one wallpaper for a given period of time. E.g. a different wallpaper each day, ore each week etc.
What do you think ?

**Comment by cvzi** [comment] 2024-10-05 20:56
I had planed this, but I don't have the time to do it anymore.

Duplicate of #9

**Closed by cvzi** 2024-10-05 20:56 UTC
